name: CyberEnchants
main: net.cyberflame.cyberenchants.Main
description: CyberEnchants, a custom enchantment plugin
version: 1.0
author: CyberFlame

commands:
   ce:
    description: Root command
   ce reload:
    description: Reloads plugin configuration
   ce give:
    description: Command used to give players custom enchantment books
   
permissions:
    cyberenchants.give:
     description: Give a player a custom enchant 
    cyberenchants.reload:
     description: Reload the plugin configuration 